#!python

import argparse

from lord import utils

if __name__ == '__main__':
    meu_parser = argparse.ArgumentParser(description='Jogar Lord of the Rings LCG por linha de comando')
    meu_parser.add_argument('Dominio',
        metavar='dominio',
        type=str,
        choices=['base','play','ringsdb'],
        help='base | play | ringsdb')
    meu_parser.add_argument(
        '-l',
        '--list',
        action='store_true',
        help='lista algo'
    )
    meu_parser.add_argument(
        '-d',
        '--decks',
        action='store_true',
        help='opera sobre decks'
    )
    meu_parser.add_argument(
        '-c',
        '--card',
        action='store_true',
        help='opera sobre cartas'
    )
    meu_parser.add_argument(
        '-s',
        '--search',
        action='store',
        help='pesquisa algo'
    )
    meu_parser.add_argument(
        '-n',
        '--new',
        action='store_true',
        help='cria algo'
    )
    meu_parser.add_argument(
        '--view',
        action='store',
        type=int,
        help='detalha algo'
    )    

    args = meu_parser.parse_args()

    if args.Dominio == 'base':
        utils.opcao_base(args)
    if args.Dominio == 'ringsdb':
        utils.opcao_ringsdb(args)
    if args.Dominio == 'play':
        utils.opcao_play(args)